// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:8d59874c-d8b3-46f6-9bab-1faf6cc48ba6",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_2J0OTfSB0",
    "aws_user_pools_web_client_id": "372v8ra8oplavtvq0gbrik6er1",
    "aws_user_files_s3_bucket": "allyticseoul-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-2"
};




export default awsmobile;
